Vagrant.configure(2) do |config|
  config.vm.define 'suricata' do |box|
      box.vm.box = "debian/stretch64"
      box.vm.hostname = 'suricata'
      box.vm.network :private_network, ip: "192.168.10.11"
      box.vm.synced_folder ".", "/vagrant", disabled: false, type: "virtualbox"
      box.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "6144"]
       vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
      config.vm.provision "docker", images: ["redis", "docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0", "docker.elastic.co/logstash/logstash-oss:6.6.0", "jasonish/evebox"]
      config.vm.provision "shell", path: "setup.sh", privileged: false
    end
end
